(global-set-key (kbd "M-;") 'evilnc-comment-or-uncomment-lines)
(global-set-key (kbd "<f8>") 'projectile-switch-to-buffer)
(global-set-key (kbd "C-<f8>") 'ivy-switch-buffer)
(global-set-key (kbd "<f9>") 'toggle-truncate-lines)
(global-set-key (kbd "C-c k") 'counsel-yank-pop)
